{% set name = "scikit-misc" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/has2k1/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 7d5367253f2b17e330dcf0fe7afad7a6986bd6e747d45bd4727a67b7ac68cb0a

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - numpy
    - libopenblas

test:
  imports:
    - skmisc
    - skmisc.loess

about:
  home: https://github.com/has2k1/scikit-misc
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Miscellaneous tools for data analysis and scientific computing.
  doc_url: https://has2k1.github.io/scikit-misc
  dev_url: https://github.com/has2k1/scikit-misc

extra:
  recipe-maintainers:
    - yihming
    - bli25
