{% set name = "scikit-misc" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/scikit_misc/scikit_misc-{{ version }}.tar.gz
  sha256: 49fa30e4051b341edc7422db66a12c0f59d468729285bfe644d10924dc51be0a

build:
  number: 0
  skip: true  # [win or py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("fortran") }}
  host:
    - python
    - pip
    - cython
    - numpy
    - setuptools
    - meson-python
    - wheel
    - python-build
  run:
    - python
    - numpy

test:
  imports:
    - skmisc
    - skmisc.loess

about:
  home: https://github.com/has2k1/scikit-misc
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Miscellaneous tools for data analysis and scientific computing.
  doc_url: https://has2k1.github.io/scikit-misc
  dev_url: https://github.com/has2k1/scikit-misc

extra:
  recipe-maintainers:
    - has2k1
    - yihming
    - bli25
