{% set name = "scikit-misc" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/has2k1/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 4f63fdbbd12a45b0a515df5a693471092faa3f9558f16b6ffbe465b5688cc56b

build:
  number: 0
  skip: true  # [win or py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("fortran") }}
  host:
    - python
    - pip
    - cython
    - numpy
    - setuptools
  run:
    - python
    - numpy
    - libopenblas

test:
  imports:
    - skmisc
    - skmisc.loess

about:
  home: https://github.com/has2k1/scikit-misc
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Miscellaneous tools for data analysis and scientific computing.
  doc_url: https://has2k1.github.io/scikit-misc
  dev_url: https://github.com/has2k1/scikit-misc

extra:
  recipe-maintainers:
    - yihming
    - bli25
