context:
  version: 0.5.1

package:
  name: scikit-misc
  version: ${{ version }}

source:
  url: https://github.com/has2k1/scikit-misc/archive/v${{ version }}.tar.gz
  sha256: 1481be38c93e6a9913d3beb3dddaa7b57158abfc412599b82b9e3ece7930ce70

build:
  number: 5
  script: ${{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('fortran') }}
    - ${{ stdlib('c') }}
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - python
  host:
    - meson-python
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - numpy
    - libopenblas

tests:
  - python:
      imports:
        - skmisc
        - skmisc.loess

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Miscellaneous tools for data analysis and scientific computing.
  homepage: https://github.com/has2k1/scikit-misc
  repository: https://github.com/has2k1/scikit-misc
  documentation: https://has2k1.github.io/scikit-misc

extra:
  recipe-maintainers:
    - danielnachun
    - yihming
    - bli25
